### ISSUE TITLE
Launch Stack points to outdated version that no longer deploys successfully

### ISSUE THREAD

**Issue by StevenSmiley** [DataDog/serverless-sample-app#15]
## Expected Behavior
Launch Stack would deploy a working version of the app

## Actual Behavior
The CloudFormation deployment fails because the SQSConsumerFunction uses an unsupported version of nodejs (12.x)

## Steps to Reproduce the Problem

  1. Click launch stack
  2. View the CloudFormation console events

**Comment by purple4reina** [comment]
Hey @StevenSmiley, we've made some pretty significant changes to this repo since you opened this issue. Can you let us know if this is still an issue. Otherwise, we will go ahead and close this issue.
